### ISSUE TITLE
Switch to major.minor.bugfix versioning

### ISSUE THREAD

**Issue by rsignell-usgs** [nctoolbox/nctoolbox#54]
Can we switch to major.minor.bugfix versioning?

I'd like to bugfix the stable release, but that's awkward with the current versioning syntax.    Since the stable release is called "nctoolbox-20140305", if I bugfix it, I'd have to call it  "nctoolbox-20140305-r2" or something.

How about we replace the existing tags with 

nctoolbox-20140414-beta  =>  v1.2-DEV
nctoolbox-20130305     =>  v1.0.1

Then I can create a v1.0.x branch that I can commit to from the v1.0.1 tag, and after bugfixing, I can tag as v1.0.2.     I can't apply these fixes to master as they no longer work.

Sound okay?   We would have to modify the links in the https://github.com/nctoolbox/nctoolbox/blob/gh-pages/index.html to point to these tags instead. 

I guess we could just add new tags, leaving the old ones there also, but that seems confusing.

**Comment by rsignell-usgs** [comment]
I'm continuing the [discussion about release branches here](https://github.com/nctoolbox/nctoolbox/issues/61#issuecomment-71931554) because it's related to the semantic versioning decision, not grib. 

So you guys are the developers, not me, but the reason I thought this was a good idea was because of the problem I was faced with:  I wanted to bugfix an old release without adding the new functionality from master.   

It seems that this a [common git approach[(http://svnbook.red-bean.com/en/1.7/svn.branchmerge.commonpatterns.html)

It's also used on other projects like ipython, matlplotlib and the [British Met Office python Iris package](https://github.com/SciTools/iris).  

Sure this is a smaller project, but why not do it right?

**Comment by hohonuuli** [comment]
Hi Rich, I've got to say I'm very glad you're taking an interest in this. (Some one has too :-) )

The branch per release approach, which you linked to, is common in [subversion](https://subversion.apache.org/) due to the nature of svn. For svn creating a tag or branch are essentially the same thing, you create a new directory in your svn repo that contains a copy of your entire project. It's a true pain in the ass to merge changes between tags or branches in svn, so each branch truly is a diverging branch. 

git works a bit different; tagging and branching in git are almost trivial operations compared to what's involved in svn. The workflow I like to follow is described at [http://nvie.com/posts/a-successful-git-branching-model/](http://nvie.com/posts/a-successful-git-branching-model/) and more than you'll ever want to know about git workflows can be found at [https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) The key point in this git workflow is that, for the most part, releases are [tagged](http://git-scm.com/book/en/v2/Git-Basics-Tagging) on the master branch. If you need to patch a release, you can checkout that tag, then create a branch from that changeset and apply the fix. You could then either merge that changeset back into master or at that point keep a separate branch for the diverging code base. In any case git allows you to create something less like branching and more like a web.

**Comment by rsignell-usgs** [comment]
@hohonuuli , so I thought the procedure outlined in the latter part of your message was exactly what I did:  I checked out the 20130305 tag, patched it, and then kept 1.0.x separate branch because the codebase had diverged. 

sorry to be so dense.

**Comment by hohonuuli** [comment]
@rsignell-usgs It's not just you whose being dense. Apparently, I haven't been following what you did close enough. So, good to know you're doing the right thing.
